# Generated by Django 4.1 on 2023-05-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flat_no", models.CharField(max_length=10)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flat",
                "verbose_name_plural": "Flats",
            },
        ),
    ]
