# Generated by Django 4.1 on 2023-05-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flat",
            name="occupiedPeriod",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="flat",
            name="vacant",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="flat",
            name="vacantPeriod",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
