# Generated by Django 4.1 on 2023-05-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flats", "0002_flat_occupiedperiod_flat_vacant_flat_vacantperiod"),
    ]

    operations = [
        migrations.AddField(
            model_name="flat",
            name="unitPrice",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
