# Generated by Django 4.1 on 2023-06-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flats", "0005_rename_depositpymt_flat_maintenacefee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sewage",
            name="unitPrice",
            field=models.DecimalField(decimal_places=2, default=70, max_digits=10),
        ),
        migrations.AlterField(
            model_name="water",
            name="unitPrice",
            field=models.DecimalField(decimal_places=2, default=40, max_digits=10),
        ),
    ]
