# Generated by Django 4.1 on 2023-06-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flats", "0006_alter_sewage_unitprice_alter_water_unitprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flat",
            name="maintenaceFee",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
