# Generated by Django 4.1 on 2023-06-02 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0010_remove_paymentlog_deposit_and_more"),
        ("flats", "0007_alter_flat_maintenacefee"),
    ]

    operations = [
        migrations.AddField(
            model_name="sewage",
            name="flat",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sewage",
                to="flats.flat",
            ),
        ),
        migrations.AddField(
            model_name="water",
            name="flat",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="water",
                to="flats.flat",
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="flat",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flat",
                to="authy.paymentlog",
            ),
        ),
    ]
