# Generated by Django 4.1 on 2023-06-02 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flats", "0010_remove_flat_payments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sewage",
            name="payments",
        ),
        migrations.RemoveField(
            model_name="water",
            name="payments",
        ),
    ]
