# Generated by Django 4.1 on 2023-06-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flats", "0011_remove_sewage_payments_remove_water_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="flat",
            name="sewageUnitCost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="flat",
            name="waterUnitCost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
