# Generated by Django 4.1 on 2023-07-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flats", "0013_flat_nos_of_bedrooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sewage",
            name="unitPrice",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="water",
            name="unitPrice",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
