# Generated by Django 4.1 on 2023-05-29 13:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0002_remove_profile_groups_alter_renterinfo_natid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cell",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region="KE", unique=True
            ),
        ),
    ]
