# Generated by Django 4.1 on 2023-05-29 13:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0003_alter_profile_cell"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cell",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="KE", unique=True
            ),
        ),
    ]
