# Generated by Django 4.1 on 2023-05-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0004_alter_profile_cell"),
    ]

    operations = [
        migrations.AddField(
            model_name="renterinfo",
            name="taxinfo",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
