# Generated by Django 4.1 on 2023-05-30 17:28

import authy.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("flats", "0001_initial"),
        ("authy", "0006_renterinfo_renterimage_id_alter_renterinfo_taxinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="renterinfo",
            name="flat",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flat",
                to="flats.flat",
            ),
        ),
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sewage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "water",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "rental_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "deposit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "maintenance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "renterInvoice",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=authy.models.invoice_dir,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="authy.renterinfo",
                    ),
                ),
            ],
        ),
    ]
