# Generated by Django 4.1 on 2023-05-30 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0007_renterinfo_flat_paymentlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentlog",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentlog",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="renterinfo",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="renterinfo",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
