# Generated by Django 4.1 on 2023-05-31 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("flats", "0004_flat_depositpymt_flat_unitpricemaintenance_and_more"),
        ("authy", "0008_paymentlog_created_paymentlog_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="renterinfo",
            name="flat",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flat",
                to="flats.flat",
            ),
        ),
    ]
