# Generated by Django 4.1 on 2023-06-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0009_alter_renterinfo_flat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentlog",
            name="deposit",
        ),
        migrations.RemoveField(
            model_name="paymentlog",
            name="maintenance",
        ),
        migrations.RemoveField(
            model_name="paymentlog",
            name="rental_fee",
        ),
        migrations.RemoveField(
            model_name="paymentlog",
            name="sewage",
        ),
        migrations.RemoveField(
            model_name="paymentlog",
            name="water",
        ),
        migrations.RemoveField(
            model_name="renterinfo",
            name="flat",
        ),
        migrations.AddField(
            model_name="paymentlog",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("complete", "Complete"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
