# Generated by Django 4.1 on 2023-06-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("flats", "0011_remove_sewage_payments_remove_water_payments"),
        ("authy", "0011_paymentlog_flat"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentlog",
            name="sewage",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sewage",
                to="flats.sewage",
            ),
        ),
        migrations.AddField(
            model_name="paymentlog",
            name="water",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="water",
                to="flats.water",
            ),
        ),
    ]
