# Generated by Django 4.1 on 2023-06-27 20:20

import authy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authy", "0013_paymentlog_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="renterinfo",
            name="taxinfo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=authy.models.render_tax_info_dir_path,
            ),
        ),
    ]
